### ISSUE TITLE
About the scale down in multihead attention

### ISSUE THREAD

**Issue by dayu11** [hongyi-zhang/Fixup#8]
Hi,

  In your implementation of transformer's multihead attention module, I notice you use L^(-1/6) to scale down the initialization of the first weight layer. Since the multihead attention module has only two weight layers, should't the scale down coefficient be set as L^(-1/2) according to the derivation in your paper?

**Comment by hongyi-zhang** [comment]
Hi,

Thanks for your discussion. Please see the explanation below:

> Since the multihead attention module has only two weight layers,

In our paper we say a network branch has `m` layers if the mapping from its input to output contains `m` sequential weight matrix multiplications. So it's reasonable to say the multihead attention module (Sec 3.2 in Transformer paper) has four weight layers, as it has the form
`MultiHead = Concat(..., Attention(QW_{i}^{Q}, KW_{i}^{K}, VW_{i}^{V}), ...) W^{O}`,
where `Attention(Q, K, V) = Softmax(Q K^T / sqrt(d)) V ~= Q K^T V / sqrt(d)` contains three weight layers and `W^{O}` is the fourth layer. 

> I notice you use L^(-1/6) to scale down the initialization of the first weight layer

As explained in the above text, `L^(-1/6)` is used to scale down the initialization of the first _three_ weight layers `W^{Q}, W^{K}` and `W^{V}`, whereas `W^{O}` is initialized as zero.

Hope this helps to clarify! Please let me know if you have further questions.

**Comment by dayu11** [comment]
Thanks for your explanation! I have no further questions.
